### ISSUE TITLE
Unable to delete row using mobile version (tooltips get in the way - remove tooltips on mobile)

### ISSUE THREAD

**Issue by FernandoContrerasPalomar** [Tablepedia/V2-Beta#12]
I tried to delete a row in "Otitis" using the mobile version (iPhone 6s, iOS 9.3.2). Nothing happened when I clicked on the red "-" button. 

I then tried the same using the web version (Safari; mac book pro) and it worked just fine.

**Comment by contreras-jorgev** [comment]
Looks like the tooltips are getting in the way (for Mobile size). We plan to remove them (and leave them for Desktop sizes). Also we plan to grow the icons a little on the Mobile size, so that we can recognize when the user Taps on the action.

Eventually (for Mobile), we need to detect when is the FIRST time they are trying to Add/Edit a table and present them with an image/Help that shows how to perform the actions using the icons (and allow them to NOT show that again) -- This seems to be the "standard" way to teach new tools for Apps.

**Comment by contreras-jorgev** [comment]
Please verify.
