### ISSUE TITLE
Please provide the text for "Version 2 Beta" and ''Contact us' automatic e-mail responses.

### ISSUE THREAD

**Issue by contreras-jorgev** [Tablepedia/V2-Beta#46]

**Comment by contreras-jorgev** [comment]
There are two places in the Beta where people can tell us that they are interested:
1. Thru 'Version 2 Beta' disclaimer
2. By selecting 'Contact us'

We will send emails, saying that we are happy to provide either notification when Tablepedia V2 its released, or general Feedback.

Please design the content. Remember that we need two translations (English and Spanish)

**Comment by contreras-jorgev** [comment]
Tablepedia sent its first e-mail (test) to a "prospect":

![email-tablepedia](https://cloud.githubusercontent.com/assets/7340244/16168348/b80a2320-34c9-11e6-9d30-f368adf9f6d3.png)

**Comment by contreras-jorgev** [comment]
There are three places where e-maila may be sent:
1. Thru 'Version 2 Beta' disclaimer
2. By selecting 'Contact us'
3. Register (creator)

**Comment by FernandoContrerasPalomar** [comment]
Actually there is a 4th place: 
1. Add Table button

I have documented the content for the e-mails that shall be sent in each of the 4 scenarios:
https://docs.google.com/document/d/1UXl8YNWg-6rGZH91DeptArbz6sPvFIqxA9jsG7L-G3s/edit?usp=sharing

The relevant text is in purple. Note that we only need 2 different e-mail templates for now. Scenarios 1, 3, and 4 use one template, while scenario 2 uses another template.

I also noted that we currently show the same page whether the user enters scenario 3 or 4. Scenario 3 should have its own page. I have documented the contents of such page in the same document, under "Register" button.

Let me know if you have any questions. Thanks!

**Comment by FernandoContrerasPalomar** [comment]
Rather than referencing the google docs document, please use the following templates through the Mandrill API:

For Contact Us:
"feedback-received-english"
"feedback-received-spanish"

For the other scenarios:
"thanks-for-your-interest-english"
"thanks-for-your-interest-spanish"

Use the sendTemplate function (not "send-template". This seems to be a mistake of the API documentation. For template_name, use the corresponding name from the list above. Note that you will have to pass in a template_content, even though none of these templates use this. So feel free to pass whatever for this argument.

Please do not define any "subject" within the "message" array, such that the default subject within the template is used.

Thanks
